apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:57W0CWBsQLksJV8K/7tdfLnCFsrJ0CESgcdwsYkKT/5AYhsmEsxuaUj2Z5XhuQ62XvDAqxXqp3TygFvB,iv:1MLYHkkiFXHyYlrPsTHJ0k2aQIlhatHHIqXcS7+sYuk=,tag:7o3R2aTb2sw0yffZkHow4A==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:kXa7R6Z5OudNNTaF28EniQ14Kn8=,iv:aRIZe+vG5ZnaBSKJQuCxEKRMy51LrRj8FrkPTKiKosM=,tag:yUvG84DwcR056cOXsCrI8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaHJYU01EZnJrVGZmRVFk
            UEcrVUZWU2FxUkNmNVRpaHZUcW9WL0l4dFJFCmtvVjZjTzFIOHpXZTdMdlhCbkQv
            aWdhbEJzazBRTVBpRVEzVmVlZmY2QkkKLS0tIDVlZm1meC9SOGE4WVlTY29EMU1Z
            UzZDeklXWG9DcHBFSnpKK0dSRW1wQ1EK4Kt4NSiqx27to0xSnSb5GWV9AVKFU0pX
            fC8k0GwaN9EfX89aqv9fZ2G98tBaI12fYkUi89F3L2B+R930CcWxtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1368kjlrmkc60ucqtec3u4s0hx4eczzf2q9vvd6u34rsaqs436qeqnfvsej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T23:07:08Z"
    mac: ENC[AES256_GCM,data:03vpINLRO4BBm7qMVYqeql/Td3t+mKhYyn+OGvnqjgTLJV+cILiiY8dcLfL/YzCG645Bw7sgoQCCbi+MG0d+XlmhMeR3a75ffAXFAZEWyU1TjZnTlC8RanjM6L2WAw4eOOG5kJFAyW2vh4eUGHMrIpXbDCMmVpkaRdef2NPXcyQ=,iv:bRGlz0ejxz+iH6hYx98gjXGhQ+9EyUHSK4LCtLBmQHY=,tag:i4GjoBVzWeULzhRzxWa1EQ==,type:str]
    version: 3.13.3
