apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:dKpJF77fqRSnZWPeGFT6RKUEBJXDe46UeuFo5HC/T2aCZHIClJmYLWsRcwzlvaj4ELflX7gilG/vs91Q,iv:sdbGjz2thex4NYP5RvAQCaNwFmb/8YEHvKR9tmL9If8=,tag:VtjjUROvxaup8Kgk+4ul8Q==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:kXa7R6Z5OudNNTaF28EniQ14Kn8=,iv:aRIZe+vG5ZnaBSKJQuCxEKRMy51LrRj8FrkPTKiKosM=,tag:yUvG84DwcR056cOXsCrI8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaHJYU01EZnJrVGZmRVFk
            UEcrVUZWU2FxUkNmNVRpaHZUcW9WL0l4dFJFCmtvVjZjTzFIOHpXZTdMdlhCbkQv
            aWdhbEJzazBRTVBpRVEzVmVlZmY2QkkKLS0tIDVlZm1meC9SOGE4WVlTY29EMU1Z
            UzZDeklXWG9DcHBFSnpKK0dSRW1wQ1EK4Kt4NSiqx27to0xSnSb5GWV9AVKFU0pX
            fC8k0GwaN9EfX89aqv9fZ2G98tBaI12fYkUi89F3L2B+R930CcWxtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1368kjlrmkc60ucqtec3u4s0hx4eczzf2q9vvd6u34rsaqs436qeqnfvsej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T22:58:35Z"
    mac: ENC[AES256_GCM,data:OR4W6xJwRI5LUlaY6V5Q2WlEkiQhj0AT+0kVuktFJRcSu2l6utkJqnWPggyLQHHlm4Y/++bGZkrcHh4bMOIWcaqoURcTwvbW0KahQE5uGg9B8nQCE+H5s12LupXAj9qGOMnqpJzbBGNEaqkoPv6DCd/sS5YTNVpbic3RjRPo6zw=,iv:YmLYZsU8bcfN1vcSIymJhEOE0ZDMUzJn9CG4Htl1LAY=,tag:Ty+WQajudxCFCVe7V8jb7Q==,type:str]
    version: 3.13.3
