apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:UoUTcoo=,iv:Lf5FIucOGCmiVm/JoPq+6oI8Hylbz4KYi41nsm3Jz7E=,tag:oak2jxdzg8+kYji16bA5tg==,type:str]
    admin-password: ENC[AES256_GCM,data:XAYqu9hdDcw=,iv:cDuLqZfNBRfT1e3TphLBfdIo8D3w4q7Ct6qi0bZ9ws8=,tag:8x7e0iot791Nw1q3C9smWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnNDenpuN0lWUEpjRzFJ
            VTUrVWxpdzYrWkhmNlBrbTUzU0JXSWhKUEFjCjdVWlV5c1ZlV2RrTGovS0NZRGRu
            eGRUTFMxbGFkem1TMTV0R0w1Q1VUa2cKLS0tIHJJVEh3UmJHTnQvM21tbW9Hc0l5
            eU9kZDVFbG9EWkVSWUV1ZzJNNHRWS28K7rp+9bBJkUSmYk4j536v2VIkpc/S/ER5
            7p6CSXD7jLYPPM2B0s0XQvoO5ERIKs3hbdXazvkMVWR3Asq+qIhRnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1368kjlrmkc60ucqtec3u4s0hx4eczzf2q9vvd6u34rsaqs436qeqnfvsej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T20:35:03Z"
    mac: ENC[AES256_GCM,data:bNpQQrtlUVTFjLWtFkzE2Q0sPj3KqlAiK4/dctTZl+5/TQPaZ7DCCyKE6eNFYXRxqSAwFFS32oopNFafUxZktca0VIsNpAfYqk55yK6S4hwqPZpvYwt1JW3B3WO4fm1QD2j6WU1H0LoeVduejBvMpkbwOSSXAvjF0xc3EAeGjD8=,iv:j0AuFzw1o+a4FsTnsCSjNWrcY6CnDDM1ITKuEr0MV4s=,tag:dCp98BgnWPV1wea92x6M2w==,type:str]
    version: 3.13.3
