apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:UoUTcoo=,iv:Lf5FIucOGCmiVm/JoPq+6oI8Hylbz4KYi41nsm3Jz7E=,tag:oak2jxdzg8+kYji16bA5tg==,type:str]
    admin-password: ENC[AES256_GCM,data:NhKIf6ZIsggCFBN8R/4=,iv:xd56n6Tm6550HJgBVNzpth/BGKdvsCIEwLRpIduEqW4=,tag:mksMEXD/tne1QPVSi0rqYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnNDenpuN0lWUEpjRzFJ
            VTUrVWxpdzYrWkhmNlBrbTUzU0JXSWhKUEFjCjdVWlV5c1ZlV2RrTGovS0NZRGRu
            eGRUTFMxbGFkem1TMTV0R0w1Q1VUa2cKLS0tIHJJVEh3UmJHTnQvM21tbW9Hc0l5
            eU9kZDVFbG9EWkVSWUV1ZzJNNHRWS28K7rp+9bBJkUSmYk4j536v2VIkpc/S/ER5
            7p6CSXD7jLYPPM2B0s0XQvoO5ERIKs3hbdXazvkMVWR3Asq+qIhRnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1368kjlrmkc60ucqtec3u4s0hx4eczzf2q9vvd6u34rsaqs436qeqnfvsej
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T21:10:44Z"
    mac: ENC[AES256_GCM,data:nH2WnIYBaYfMHEt5SuaIdglDpjlIHvcHJre3p0g4GEP5y21JyrVrQAu6D06AO1faLq2lOmyppUSj7vifgxe5Bk3oTR3mlV85x32fpwcdOuRp2+HX93NWWsJD8lFGE4L4xstu58XSub1Mh+0Ksq9x9zXivqkc7qhM8WLk2QV8Xt0=,iv:L18PZVEbC5sc5YJSSMBXJtYvhTelCiBKuggEDl+viOo=,tag:ZXYqrEFIulCrs4MHMw2oTw==,type:str]
    version: 3.13.3
