---
- name: Apply encrypted secrets
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    sops_key_file: "{{ lookup('env','HOME') }}/.config/sops/age/keys.txt"
    secrets_dir: "{{ playbook_dir }}/../gitops/secrets"

  tasks:

    - name: Find encrypted secrets
      find:
        paths: "{{ secrets_dir }}"
        patterns: "*.enc.yaml"
      register: encrypted_secrets

    - name: Decrypt secrets
      ansible.builtin.command:
        cmd: sops --decrypt {{ item.path }}
      environment:
        SOPS_AGE_KEY_FILE: "{{ sops_key_file }}"
      register: decrypted_secret
      loop: "{{ encrypted_secrets.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Apply decrypted secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ item.stdout | from_yaml }}"
      loop: "{{ decrypted_secret.results }}"
      loop_control:
        label: "{{ item.item.path }}"
